name: docsvibe-backend
region: blr
services:
  - name: api
    source_dir: backend
    github:
      repo: Kushal-Raj-G-S/DocsVibe-AI-Powered-Document-Chat
      branch: main
      deploy_on_push: true
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    health_check:
      http_path: /health
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: R2_ACCOUNT_ID
        scope: RUN_TIME
        type: SECRET
      - key: R2_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: R2_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: R2_BUCKET_NAME
        scope: RUN_TIME
        value: "docsvibe-documents"
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
